nameOverride: ""
fullnameOverride: "interview-coach-backend"

replicaCount: 1

image:
  repository: sirlazybone/interview-backend
  tag: main-25-cc4543e
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub-pull-secret

service:
  type: ClusterIP
  port: 8080

resources: {}

env:
  serverPort: 8080
  jwtIssuer: interview-coach
  jwtAccessTokenMinutes: 15
  jwtRefreshTokenDays: 7
  emailVerificationExpirationMinutes: 15
  emailVerificationMaxAttempts: 5
  corsAllowedOrigins: https://interview-coach.ru
  mailEnabled: true
  mailFrom: andberezutsky@gmail.com
  mailVerificationSubject: Interview Coach email verification
  mailResetSubject: Interview Coach password reset
  frontendPasswordResetUrl: https://interview-coach.ru/reset-password
  springMailHost: smtp.gmail.com
  springMailPort: 587
  springMailUsername: andberezutsky@gmail.com
  springMailSmtpAuth: true
  springMailSmtpStarttls: true
  managementTracingSamplingProbability: "1.0"
  managementOtlpTracingEndpoint: http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces
  assessmentEnabled: true
  assessmentBaseUrl: https://daringly-ammonium-shank.ngrok-free.dev
  assessmentApiKey: demo-api-key
  assessmentClientId: main-backend
  assessmentMetadataSource: main-backend
  assessmentMode: async
  assessmentQuestionLimit: 20
  assessmentReportAttempts: 20
  assessmentPollDelayMillis: 120000
  assessmentCircuitBreakerFailureThreshold: 3
  assessmentCircuitBreakerOpenDuration: 60
  assessmentReportLanguage: ru
  assessmentSubscriptionPlan: start

secrets:
  create: false
  jwtSecret: ""
  springMailPassword: ""

externalSecrets:
  enabled: true
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  targetSecretName: ""
  data:
    - secretKey: APP_SECURITY_JWT_SECRET
      remoteRef:
        key: interview-coach/backend
        property: APP_SECURITY_JWT_SECRET
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: interview-coach/postgres
        property: POSTGRES_PASSWORD
    - secretKey: SPRING_MAIL_PASSWORD
      remoteRef:
        key: interview-coach/backend
        property: SPRING_MAIL_PASSWORD

database:
  host: interview-coach-postgres
  port: 5432
  name: interview_coach
  username: interview_coach
  password: ""

probes:
  readiness:
    path: /api/actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    path: /api/actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 15

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: api.interview-coach.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.interview-coach.ru
      secretName: interview-coach-backend-tls
