nameOverride: ""
fullnameOverride: "interview-coach-backend"

replicaCount: 1

image:
  repository: sirlazybone/interview-backend
  tag: main-13-8a36bea
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub-pull-secret

service:
  type: ClusterIP
  port: 8080

resources: {}

env:
  serverPort: 8080
  jwtIssuer: interview-coach
  jwtAccessTokenMinutes: 15
  jwtRefreshTokenDays: 7
  emailVerificationExpirationMinutes: 15
  emailVerificationMaxAttempts: 5
  corsAllowedOrigins: https://interview-coach.ru
  mailEnabled: true
  mailFrom: interview-coach@inbox.ru
  mailVerificationSubject: Interview Coach email verification
  mailResetSubject: Interview Coach password reset
  frontendPasswordResetUrl: https://interview-coach.ru/reset-password
  springMailHost: smtp.mail.ru
  springMailPort: 465
  springMailUsername: interview-coach@inbox.ru
  springMailSmtpAuth: true
  springMailSmtpStarttls: true
  managementTracingSamplingProbability: "1.0"
  managementOtlpTracingEndpoint: http://otel-collector.monitoring.svc.cluster.local:4318/v1/traces
  assessmentEnabled: true
  assessmentBaseUrl: http://89.124.115.112:8000
  assessmentApiKey: demo-api-key
  assessmentClientId: main-backend
  assessmentMetadataSource: main-backend
  assessmentMode: sync
  assessmentQuestionLimit: 20
  assessmentReportAttempts: 20
  assessmentPollDelayMillis: 120000
  assessmentCircuitBreakerFailureThreshold: 3
  assessmentCircuitBreakerOpenDuration: 60
  assessmentReportLanguage: ru
  assessmentSubscriptionPlan: start

secrets:
  jwtSecret: change-me-very-long-random-jwt-secret
  springMailPassword: CyjV3xr8yc02QrhxJNdL

database:
  host: interview-coach-postgres
  port: 5432
  name: interview_coach
  username: interview_coach
  password: interview_coach

probes:
  readiness:
    path: /api/actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 10
  liveness:
    path: /api/actuator/health/liveness
    initialDelaySeconds: 30
    periodSeconds: 15

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: api.interview-coach.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.interview-coach.ru
      secretName: interview-coach-backend-tls
