alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  fullnameOverride: prometheus
  persistentVolume:
    enabled: true
    size: 10Gi
    # storageClass: local-path

serverFiles:
  alerts.yml:
    groups: []

extraScrapeConfigs: |
  - job_name: interview-coach-backend
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets:
          - interview-coach-backend.app.svc.cluster.local:8080
