nameOverride: ""
fullnameOverride: "vault"

image:
  repository: hashicorp/vault
  tag: "1.21.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8200

persistence:
  size: 2Gi
  storageClass: ""

resources: {}
