apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "interview-coach-ingress-nginx.configMapName" . }}
  labels:
    {{- include "interview-coach-ingress-nginx.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.controller.config | nindent 2 }}
