apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.controller.ingressClass.name }}
  labels:
    {{- include "interview-coach-ingress-nginx.labels" . | nindent 4 }}
spec:
  controller: {{ .Values.controller.ingressClass.controllerValue }}
