{{- if .Values.controller.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "interview-coach-ingress-nginx.serviceAccountName" . }}
  labels:
    {{- include "interview-coach-ingress-nginx.labels" . | nindent 4 }}
{{- end }}
