nameOverride: ""
fullnameOverride: "interview-coach-frontend"

replicaCount: 2

image:
  repository: sirlazybone/interview-frontend
  tag: main-20-53f7b32
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub-pull-secret

runtimeConfig:
  apiBaseUrl: https://api.interview-coach.ru/api

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: interview-coach.ru
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - interview-coach.ru
      secretName: interview-coach-frontend-tls

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
