nameOverride: ""
fullnameOverride: "interview-coach-frontend"

replicaCount: 2

image:
  repository: sirlazybone/interview-frontend
  tag: 0.1.4
  pullPolicy: IfNotPresent

imagePullSecrets: []

runtimeConfig:
  apiBaseUrl: http://api.interview-coach.ru/api

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: interview-coach.ru
      paths:
        - path: /
          pathType: Prefix
  tls: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
