apiVersion: v1
kind: Secret
metadata:
  name: {{ include "interview-coach-backend.secretName" . }}
  labels:
    {{- include "interview-coach-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECURITY_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.secrets.springMailPassword | quote }}
