apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-config
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  vault.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/file"
    }

    api_addr = "http://{{ include "vault.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8200"
    cluster_addr = "http://127.0.0.1:8201"
