apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vault.fullname" . }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "vault.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vault.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - vault
            - server
            - -config=/vault/config/vault.hcl
          env:
            - name: VAULT_ADDR
              value: http://127.0.0.1:8200
            - name: VAULT_API_ADDR
              value: http://{{ include "vault.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8200
            - name: SKIP_CHOWN
              value: "true"
            - name: SKIP_SETCAP
              value: "true"
          ports:
            - name: http
              containerPort: 8200
            - name: cluster
              containerPort: 8201
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - vault status >/dev/null 2>&1; code="$?"; [ "$code" -eq 0 ] || [ "$code" -eq 2 ]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/file
      volumes:
        - name: config
          configMap:
            name: {{ include "vault.fullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
