apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    vault:
      server: {{ .Values.secretStore.vault.server | quote }}
      path: {{ .Values.secretStore.vault.path | quote }}
      version: {{ .Values.secretStore.vault.version | quote }}
      auth:
        kubernetes:
          mountPath: {{ .Values.secretStore.vault.kubernetesMountPath | quote }}
          role: {{ .Values.secretStore.vault.role | quote }}
          serviceAccountRef:
            name: {{ .Values.secretStore.vault.serviceAccount.name | quote }}
            namespace: {{ .Values.secretStore.vault.serviceAccount.namespace | quote }}
